### ISSUE TITLE
PDF exports maken

### ISSUE THREAD

**Issue by EricBurgers63** [woutergeurts/sysml-workshop#1]
In de Linux Mint omgeving moeten inkscape en pandoc en LaTeX worden geïnstalleerd. Nodig om pdf-en te maken. target: modeller VM

**Comment by woutergeurts** [comment]
ga ik naar kijken, In mijn omgeving kan ik ook 'print to pdf' doen

**Comment by woutergeurts** [comment]
De linux mint omgeving is bijgewerkt
